import {
  FaFolderOpen,
  FaMedium,
  FaGithub,
  FaLinkedin,
  FaMicrophone,
  FaHeadphones,
  FaFilm,
} from "react-icons/fa";
import { SiHashnode } from "react-icons/si";

const imageData = [
  {
    name: "Portfolio",
    title: "My Work",
    description: "Showcasing my projects and skills.",
    link: "/portfolio",
    buttonText: "View Portfolio",
    color: "#1a1a1a",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "3deg",
    icon: FaFolderOpen,
    tags: ["Projects", "Full-Stack", "React", "Go"],
  },
    {
    name: "Chroma Town",
    title: "Mafia Game Coordination",
    description: "A web app to coordinate Mafia games with friends — one of my all-time favorite party games!",
    link: "https://chroma-town.netlify.app/",
    buttonText: "Go to Chroma Town",
    color: "#8B5E3C",
    nameColor: "#ffffff",
    textColor: "#dddddd",
    tilt: "2deg",
    icon: FaFolderOpen,
    tags: ["Games", "Party", "Fun", "Web App"]
  },
  {
    name: "Medium",
    title: "My Articles",
    description: "Read my latest Medium blog posts.",
    link: "https://medium.com/@yourusername",
    buttonText: "Read More",
    color: "#2b2b2b",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "-3deg",
    icon: FaMedium,
    tags: ["Writing", "Tech", "Guides", "Personal"],
  },
  {
    name: "Hashnode",
    title: "Old Dev Blog",
    description: "Check out my developer blog on Hashnode.",
    link: "https://hashnode.com/@yourusername",
    buttonText: "Read Blog",
    color: "#1f1f1f",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "5deg",
    icon: SiHashnode,
    tags: ["Development", "JavaScript", "Tips", "Programming"],
  },
  {
    name: "GitHub",
    title: "Code & Projects",
    description: "Explore my GitHub repositories.",
    link: "https://github.com/yourusername",
    buttonText: "View GitHub",
    color: "#141414",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "-5deg",
    icon: FaGithub,
    tags: ["Open Source", "Repos", "Code", "Collaboration"],
  },
  {
    name: "LinkedIn",
    title: "Professional Profile",
    description: "Connect with me on LinkedIn.",
    link: "https://linkedin.com/in/yourusername",
    buttonText: "Connect",
    color: "#212121",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "2deg",
    icon: FaLinkedin,
    tags: ["Networking", "Career", "Professional", "Resume"],
  },
  {
    name: "Speaking",
    title: "Events & Talks",
    description: "Watch or listen to my speaking engagements.",
    link: "/speaking",
    buttonText: "Watch Talks",
    color: "#1c1c1c",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "-4deg",
    icon: FaMicrophone,
    tags: ["Events", "Talks", "Presentations", "Public Speaking"],
  },
  {
    name: "DJ",
    title: "Music & Sets",
    description: "Listen to my DJ sets and mixes.",
    link: "/dj",
    buttonText: "Listen Now",
    color: "#2c2c2c",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "4deg",
    icon: FaHeadphones,
    tags: ["Music", "DJ Sets", "Mixes", "Entertainment"],
  },
  {
    name: "Movies",
    title: "Movies I Love",
    description: "A collection of movies that inspire me.",
    link: "/movies",
    buttonText: "See Collection",
    color: "#1e1e1e",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "-2deg",
    icon: FaFilm,
    tags: ["Inspiration", "Cinema", "Favorites", "Storytelling"],
  },
  {
    name: "Languages",
    title: "Trilingual",
    description: "I speak English, French, and Yoruba fluently.",
    link: "/languages",
    buttonText: "Learn More",
    color: "#1f1f1f",
    nameColor: "#ffffff",
    textColor: "#aaaaaa",
    tilt: "1deg",
    icon: FaMicrophone,
    tags: ["English", "French", "Yoruba"],
  },
];

export default imageData;
